[versions]
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "36"

agp = "9.0.0"
kotlin = "2.3.0"
ksp = "2.3.4"
coroutine = "1.10.2"
compose-bom = "2026.01.00"
hilt = "2.58"
room = "2.8.4"
ktor = "3.3.3"
ktx-serialize = "1.9.0"

activity = "1.12.2"
lifecycle = "2.10.0"
core = "1.17.0"
appcompat = "1.7.1"
constraint-layout = "2.2.1"
# constraintlayoutCompose = "1.1.0"
recyclerview = "1.4.0"
browser = "1.9.0"
splashscreen = "1.2.0"
navigation = "2.9.6"
navigation-animation = "0.36.0"

okhttp = "5.3.2"
retrofit = "3.0.0"
coil = "3.3.0"
workManager = "2.11.0"
# leakcanary = "2.14"
# bugly = "4.1.9.3"

[libraries]
# coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutine" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutine" }

hilt-core = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
# hilt-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }

compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
# 使用「Android Studio」调试、交互的预览界面需要引用此库，应该「debug」引用
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
# 使用@Preview需要引用此库
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
# compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-material-icons = { group = "androidx.compose.material", name = "material-icons-extended" }

room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }

androidx-activity = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }
# androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraint-layout" }
# androidx-constraintlayout-compose = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraintlayoutCompose" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-browser = { group = "androidx.browser", name = "browser", version.ref = "browser" }
androidx-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "splashscreen" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
accompanist-navigation-animation = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "navigation-animation" }
androidx-work-manager = { module = "androidx.work:work-runtime-ktx", version.ref = "workManager" }

retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
retrofit-scalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "retrofit" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
# retrofit-mock = { group = "com.squareup.retrofit2", name = "retrofit-mock", version.ref = "retrofit" }

coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-okhttp = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil" }
coil-svg = { group = "io.coil-kt.coil3", name = "coil-svg", version.ref = "coil" }

# leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }
# leakcanary-no-op = { module = "com.squareup.leakcanary:leakcanary-android-no-op", version.ref = "leakcanary" }
# bugly = { module = "com.tencent.bugly:crashreport", version.ref = "bugly" }

ktor-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-serialize = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-android = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
kotlinx-serilize = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "ktx-serialize" }

[bundles]
androidx = ["androidx-lifecycle-viewmodel-compose", "androidx-lifecycle-runtime-ktx", "androidx-activity-compose", "androidx-core-ktx", "androidx-appcompat"]
compose = ["compose-material3", "compose-ui-tooling-preview"]
coil = ["coil-compose", "coil-okhttp", "coil-svg"]
retrofit = ["retrofit", "retrofit-gson", "retrofit-scalars", "okhttp-logging"]
room = ["room-ktx", "room-runtime"]
navigation = ["accompanist-navigation-animation", "androidx-navigation-compose"]
kmp = ["ktor-core", "ktor-negotiation", "ktor-serialize", "ktor-android", "kotlinx-serilize"]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
serialize = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }